import { useState } from 'react';
import { Play, MoreVertical, Plus, GripVertical, CheckCircle2, X } from 'lucide-react';
import { useStudyPlanner } from '../lib/store';
import { createCalendarEvent } from '../lib/calendar';

const colorMap: Record<string, { border: string, bg: string, text: string }> = {
  blue: { border: 'border-blue-500', bg: 'bg-blue-500', text: 'text-blue-400' },
  purple: { border: 'border-purple-500', bg: 'bg-purple-500', text: 'text-purple-400' },
  green: { border: 'border-green-500', bg: 'bg-green-500', text: 'text-green-400' },
  orange: { border: 'border-orange-500', bg: 'bg-orange-500', text: 'text-orange-400' },
  red: { border: 'border-red-500', bg: 'bg-red-500', text: 'text-red-400' },
  cyan: { border: 'border-cyan-500', bg: 'bg-cyan-500', text: 'text-cyan-400' },
};

export default function StudyPlanner() {
  const { subjects, addSubject, addSession, toggleSession, deleteSession, getProgress } = useStudyPlanner();
  
  const [isAddingSubject, setIsAddingSubject] = useState(false);
  const [newSubjectTitle, setNewSubjectTitle] = useState('');
  
  const [isAddingSession, setIsAddingSession] = useState<string | null>(null); // subjectId
  const [newSessionTitle, setNewSessionTitle] = useState('');

  const [isSyncing, setIsSyncing] = useState(false);

  const handleAddSubject = () => {
    if (newSubjectTitle.trim()) {
      const colors = ['blue', 'purple', 'green', 'orange', 'red'];
      const color = colors[Math.floor(Math.random() * colors.length)];
      addSubject(newSubjectTitle.trim(), color);
      setNewSubjectTitle('');
      setIsAddingSubject(false);
    }
  };

  const handleAddSession = (subjectId: string, day: string) => {
    if (newSessionTitle.trim()) {
      addSession(subjectId, newSessionTitle.trim(), day, 1);
      setNewSessionTitle('');
      setIsAddingSession(null);
    }
  };

  const handleSyncToCalendar = async () => {
    setIsSyncing(true);
    try {
      // Very simple sync simulation:
      // Loop through all uncompleted sessions and sync them to today + offset
      let offsetDays = 1;
      for (const subject of subjects) {
        for (const session of subject.sessions.filter(s => !s.completed)) {
          const date = new Date();
          date.setDate(date.getDate() + offsetDays);
          date.setHours(14, 0, 0, 0); // 2 PM default
          const endDate = new Date(date);
          endDate.setHours(date.getHours() + session.hours);
          
          await createCalendarEvent(`Study: ${subject.title} - ${session.topic}`, date, endDate, `Generated by Study Planner`);
          offsetDays++;
        }
      }
      alert('Successfully synced all planned sessions to Google Calendar!');
    } catch (err: any) {
      alert(`Error syncing: ${err.message || 'Please sign in first.'}`);
    } finally {
      setIsSyncing(false);
    }
  };

  const days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'];

  return (
    <div className="max-w-5xl mx-auto space-y-8">
       <header className="pt-4 pb-6 border-b border-[#2C2C2C] flex flex-wrap items-center justify-between gap-4">
         <div>
           <h1 className="text-2xl sm:text-3xl font-semibold mb-2">Study Planner</h1>
           <p className="text-[var(--text-secondary)]">Organize your study sessions and track your progress.</p>
         </div>
         <button 
           onClick={handleSyncToCalendar}
           disabled={isSyncing}
           className="px-5 py-2 gradient-animated text-white rounded-md text-sm font-medium shadow-lg hover:opacity-90 transition-opacity disabled:opacity-50"
         >
            {isSyncing ? 'Syncing...' : 'Finalize & Sync to Calendar'}
         </button>
       </header>

       <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
         {/* Subject Overview */}
         <div className="md:col-span-1 space-y-4">
            <h2 className="font-medium">Subjects</h2>
            <div className="space-y-3">
               {subjects.map((s) => (
                  <div key={s.id} className={`p-4 rounded-xl border border-[#333] bg-[#222] border-l-4 ${colorMap[s.color]?.border || 'border-blue-500'}`}>
                     <div className="flex justify-between items-center mb-3">
                        <span className="font-medium text-sm">{s.title}</span>
                        <MoreVertical className="w-4 h-4 text-gray-500 cursor-pointer hover:text-white" />
                     </div>
                     <div className="w-full bg-[#111] rounded-full h-1.5 overflow-hidden">
                        <div className={`h-full ${colorMap[s.color]?.bg || 'bg-blue-500'}`} style={{ width: `${getProgress(s.id)}%` }}></div>
                     </div>
                     <div className="mt-2 text-xs text-gray-400 text-right">{getProgress(s.id)}% ready</div>
                  </div>
               ))}
               
               {isAddingSubject ? (
                 <div className="flex items-center gap-2 p-3 rounded-xl border border-[#444] bg-[#222]">
                   <input
                     autoFocus
                     type="text"
                     value={newSubjectTitle}
                     onChange={e => setNewSubjectTitle(e.target.value)}
                     onKeyDown={e => e.key === 'Enter' && handleAddSubject()}
                     placeholder="Subject name"
                     className="flex-1 bg-transparent text-sm outline-none"
                   />
                   <button onClick={handleAddSubject} className="text-blue-400 text-sm">Add</button>
                   <button onClick={() => setIsAddingSubject(false)} className="text-gray-500 hover:text-white"><X className="w-4 h-4" /></button>
                 </div>
               ) : (
                 <button onClick={() => setIsAddingSubject(true)} className="w-full py-3 rounded-xl border border-dashed border-[#444] text-[var(--text-muted)] hover:text-white hover:border-white transition-colors text-sm flex items-center justify-center gap-2">
                   <Plus className="w-4 h-4" /> Add Subject
                 </button>
               )}
            </div>
         </div>

         {/* Board view of study sessions */}
         <div className="md:col-span-2 space-y-4">
            <h2 className="font-medium flex items-center gap-2">
              This Week's Plan 
              <span className="text-xs ml-2 px-2 py-0.5 rounded-full bg-blue-500/20 text-blue-400 border border-blue-500/30">AI Optimized</span>
            </h2>
            
            <div className="flex gap-4 overflow-x-auto pb-4 hide-scrollbar">
               {days.map(day => (
                  <div key={day} className="flex-shrink-0 w-64 bg-[#1C1C1C] rounded-xl border border-[#2C2C2C] flex flex-col">
                     <div className="p-3 border-b border-[#2C2C2C] flex justify-between items-center bg-[#222] rounded-t-xl">
                        <span className="text-sm font-medium">{day}</span>
                     </div>
                     <div className="p-3 flex-1 space-y-3 min-h-[300px]">
                        {subjects.map(s => 
                          s.sessions.filter(ss => ss.day === day).map(session => (
                            <div key={session.id} className={`bg-[#2a2a2a] p-3 rounded-lg border ${session.completed ? 'border-green-500/30 opacity-60' : 'border-[#3a3a3a]'} group cursor-grab`}>
                               <div className="flex justify-between items-start mb-2">
                                  <span className={`text-xs font-medium ${colorMap[s.color]?.text || 'text-blue-400'}`}>{s.title}</span>
                                  <button onClick={() => deleteSession(s.id, session.id)} className="opacity-0 group-hover:opacity-100 transition-opacity">
                                    <X className="w-3.5 h-3.5 text-gray-500 hover:text-red-400" />
                                  </button>
                               </div>
                               <p className={`text-sm ${session.completed ? 'line-through text-gray-500' : 'text-white'}`}>{session.topic}</p>
                               <div className="mt-3 flex items-center justify-between text-xs text-gray-400">
                                 <span>{session.hours} hrs</span>
                                 <button onClick={() => toggleSession(s.id, session.id)} className={`flex items-center gap-1 hover:opacity-80 transition-opacity ${session.completed ? 'text-gray-400' : 'text-green-400'}`}>
                                    {session.completed ? <CheckCircle2 className="w-4 h-4" /> : <><Play className="w-3 h-3" /> Start</>}
                                 </button>
                               </div>
                            </div>
                          ))
                        )}

                        {isAddingSession === day ? (
                          <div className="bg-[#2a2a2a] p-2 rounded-lg border border-blue-500">
                             <select className="w-full bg-[#111] text-xs p-1 rounded border border-[#444] mb-2 outline-none" onChange={(e) => setNewSessionTitle(e.target.value)}>
                               <option value="">Select subject...</option>
                               {subjects.map(s => <option key={s.id} value={s.id}>{s.title}</option>)}
                             </select>
                             <input
                               autoFocus
                               type="text"
                               onChange={(e) => {
                                 // Simple hack for now to store both subject and topic in state temporarily
                                 // Usually you'd use a more complex state object here
                               }}
                               onKeyDown={e => {
                                 if (e.key === 'Enter') {
                                    const select = e.currentTarget.previousElementSibling as HTMLSelectElement;
                                    if (select.value) handleAddSession(select.value, day);
                                 }
                               }}
                               placeholder="Topic (press enter)"
                               className="w-full bg-transparent text-sm outline-none mb-1 text-white placeholder-gray-500"
                             />
                             <div className="flex justify-end mt-1">
                                <button onClick={() => setIsAddingSession(null)} className="text-gray-500 hover:text-white"><X className="w-4 h-4" /></button>
                             </div>
                          </div>
                        ) : (
                          <button onClick={() => setIsAddingSession(day)} className="w-full py-2 flex justify-center text-[var(--text-muted)] hover:text-white transition-colors bg-[#222] rounded-lg border border-dashed border-[#333] hover:border-gray-500">
                             <Plus className="w-4 h-4" />
                          </button>
                        )}
                     </div>
                  </div>
               ))}
            </div>
         </div>
       </div>
    </div>
  );
}
